/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente2;

import modelos.EstadoJuego;
import modelos.EstadoJuego.Bala;
import utils.Mensaje;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

public class JuegoCliente extends JFrame {

    private EstadoJuego estado = new EstadoJuego();
    private ObjectOutputStream out;
    private ObjectInputStream in;

    private JPanel gamePanel;

    public JuegoCliente() {
        setTitle("Cliente 2 (Jugador derecha)");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        gamePanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;

                // Fondo
                g2.setColor(Color.BLACK);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // Jugador 1
                g2.setColor(Color.GREEN);
                g2.fillRect(estado.x1 - 10, estado.y1 - 20, 20, 40);

                // Jugador 2
                g2.setColor(Color.RED);
                g2.fillRect(estado.x2 - 10, estado.y2 - 20, 20, 40);

                // Balas
                g2.setColor(Color.WHITE);
                for (Bala b : estado.balas) {
                    g2.fillOval(b.x - 5, b.y - 5, 10, 10);
                }

                // Vidas
                g2.drawString("Vida J1: " + estado.vida1, 10, 15);
                g2.drawString("Vida J2: " + estado.vida2, getWidth() - 100, 15);
            }
        };

        setContentPane(gamePanel);

        gamePanel.setFocusable(true);
        gamePanel.requestFocusInWindow();
        gamePanel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                manejarTecla(e);
            }
        });

        conectar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void conectar() {
        try {
            Socket socket = new Socket("10.2.8.16", 5000);
            out = new ObjectOutputStream(socket.getOutputStream());
            out.flush();
            in = new ObjectInputStream(socket.getInputStream());

            new Thread(() -> {
            try {
                while (true) {
                    Object obj = in.readObject();
                    if (obj instanceof EstadoJuego) {
                        estado = (EstadoJuego) obj;

                        if (estado.juegoTerminado) {
                            mostrarPantallaFinal();
                            break;
                        } else {
                            SwingUtilities.invokeLater(gamePanel::repaint);
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Desconectado del servidor.");
            }
        }).start();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede conectar: " + e.getMessage());
        }
    }
    
    private void mostrarPantallaFinal() {
        SwingUtilities.invokeLater(() -> {
            getContentPane().removeAll();
            repaint();

            JPanel panelFinal = new JPanel();
            panelFinal.setLayout(new BorderLayout());

            JLabel mensaje = new JLabel(
                "Jugador " + estado.ganador + " ha ganado",
                SwingConstants.CENTER
            );
            mensaje.setFont(new Font("Arial", Font.BOLD, 32));
            mensaje.setForeground(Color.WHITE);
            panelFinal.setBackground(Color.BLACK);
            panelFinal.add(mensaje, BorderLayout.CENTER);
            
            setContentPane(panelFinal);
            revalidate();
            repaint();
        });
    }

    private void manejarTecla(KeyEvent e) {
        if (out == null) return;

        try {
            Mensaje msg = null;
            switch (e.getKeyCode()) {
                case KeyEvent.VK_UP -> msg = new Mensaje(Mensaje.Tipo.MOVER_ARRIBA, 2);
                case KeyEvent.VK_DOWN -> msg = new Mensaje(Mensaje.Tipo.MOVER_ABAJO, 2);
                case KeyEvent.VK_ENTER -> msg = new Mensaje(Mensaje.Tipo.DISPARAR, 2);
            }
            if (msg != null) {
                System.out.println("Enviando mensaje: " + msg.getTipo());
                out.writeObject(msg);
                out.flush();
            }
        } catch (Exception ignored) {}
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new JuegoCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables
}
